### ISSUE TITLE
canari install-package Malformity fails

### ISSUE THREAD

**Issue by dkovar** [digital4rensics/Malformity#3]
Greetings,

I tried installing canari and Malformity and ran into the following error. OS X 10.8, python 2.7. Both canari and Malformity were installed from source after a "git clone" today.

bash-3.2# canari install-package Malformity
Multiple versions of Maltego detected: 
[0] Maltego dev
[1] Maltego v2.0.2
[2] Maltego v3.0.4CE
[3] Maltego v3.2.0
[4] Maltego v3.3.0CE
Please select which version you wish to use [0]: 3
Looking for transforms in Malformity.transforms
Does not appear to be a valid canari package. Couldn't import the 'Malformity.transforms' package in 'Malformity'. Error message: No module named Malformity.transforms

**Comment by digital4rensics** [comment]
Pushed a couple bug fixes based on locations of files this morning. Reports say it should be fixed. Thanks!

If you still get the problem, please let me know. Also, of note, you may need to move in to the project folder after the clone in order to install the package. Shoot me an email or hit me up on twitter if that still doesn't work. Thanks.

**Comment by gmie** [comment]
Hi,
i have same problem as above..Looking for transforms in Malformity.transforms...
Does not appear to be a valid canari package. Couldn't import the 'Malformity.transforms' package in 'Malformity'. Error message: No module named Malformity.transforms

thanks

**Comment by digital4rensics** [comment]
What path are you attempting to run the command from?
